[metadata]
name = LogBar
version = 0.4.14
description = A unified Logger and ProgressBar util with zero dependencies.
long_description = file: README.md
long_description_content_type = text/markdown
author = ModelCloud
author_email = qubitium@modelcloud.ai
url = https://github.com/ModelCloud/LogBar

[options]
packages = logbar
python_requires = >=3.10
