name: Unit tests

defaults:
  run:
    shell: bash -le {0}

on:
  repository_dispatch:
  workflow_dispatch:

env:
  CUDA_DEVICE_ORDER: PCI_BUS_ID
  UV_TORCH_BACKEND: cu130
  TORCH_VERSION: 2.11.0
  PYTHON_VERSION: 3.14t
  UV_PYTHON: 3.14t

jobs:

  list-test-files:
    runs-on: ubuntu-24.04
    if: github.event.inputs.m4-only != 'true'
    outputs:
      test-files: ${{ steps.files.outputs.test-files }}
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v6

      - name: List files
        id: files
        run: |
          dir="tests"
          json_array="["

          for file in "$dir"/*; do
          [ -f "$file" ] || continue
          filename=$(basename "$file")
          if [[ "$filename" == test_*.py ]]; then
            json_array+="\"$filename\","
          fi
          done

          json_array="${json_array%,}]"

          echo "$json_array"
          echo "test-files=$json_array" >> "$GITHUB_OUTPUT"

  test:
    runs-on: [ self-hosted ]
    needs:
      - list-test-files
    container:
      image: 10.0.13.31:5000/nvidia/cuda:130-ubuntu24.04_0325
      volumes:
        - /monster/ci/env/entrypoint.sh:/entrypoint.sh
        - /monster/ci/env/entrypoint.sh:/etc/profile.d/01-entrypoint.sh
        - /dev/dri/by-path:/dev/dri/by-path
        - /monster/ci/models:/monster/data/model
        - /monster/ci/dataset:/monster/data/model/dataset
        - /monster/ci/huggingface:/github/home/.cache/huggingface
        - /monster/ci/uv:/opt/uv
        - /monster/ci/env:/opt/env
        - /monster/ci/dist:/opt/dist
    strategy:
      fail-fast: false
      matrix:
        test_script: ${{ fromJSON(needs.list-test-files.outputs.test-files) }}
    steps:
      - uses: actions/checkout@v6

      - name: Activate uv env
        run: |
          env_name="logbar_unit_test_py314t_${{ matrix.test_script }}"
          source /opt/uv/setup_uv_venv.sh $env_name

      - name: Install
        run: |
          uv pip install -U parameterized pytest pytest-xdist
          uv pip install .

      - name: test
        run: pytest -n 8 -v tests/${{ matrix.test_script }}